# Generated by Django 5.0.6 on 2024-05-29 01:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talleres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_taller', models.CharField(max_length=60)),
                ('comuna', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='agendamiento',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='agendamiento',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='agendamiento',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='agendamiento',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='agendamiento',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='agendamiento',
            name='taller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.talleres'),
        ),
    ]
